### ISSUE TITLE
新版本make报错 bind_front_handler’ is not a member of ‘boost::beast’

### ISSUE THREAD

**Issue by yutiansut** [shinnytech/open-trade-gateway#11]
root@QATRADESERVER01:/home/yutiansut/open-trade-gateway# make
g++ -o obj/trade_server.o -MMD -MP  -std=c++17 -pthread -g -O2 -flto -Icontrib/include/ -Isrc/ -c src/trade_server.cpp
src/trade_server.cpp: In member function ‘void trade_server::TradeSession::Run()’:
src/trade_server.cpp:85:9: error: ‘bind_front_handler’ is not a member of ‘boost::beast’
         boost::beast::bind_front_handler(
         ^~~~~
src/trade_server.cpp: In member function ‘void trade_server::TradeSession::DoRead()’:
src/trade_server.cpp:106:9: error: ‘bind_front_handler’ is not a member of ‘boost::beast’
         boost::beast::bind_front_handler(
         ^~~~~
src/trade_server.cpp: In member function ‘void trade_server::TradeSession::DoWrite()’:
src/trade_server.cpp:200:9: error: ‘bind_front_handler’ is not a member of ‘boost::beast’
         boost::beast::bind_front_handler(
         ^~~~~
Makefile:19: recipe for target 'obj/trade_server.o' failed
make: *** [obj/trade_server.o] Error 1

**Comment by shinny-yangyang** [comment]
从 eb831a2c6e0661863d5c8b585efd884820caa512 版本开始要求 boost 1.70
