### ISSUE TITLE
二进制分发

### ISSUE THREAD

**Issue by bigtan** [shinnytech/open-trade-gateway#13]
在release时，能否提供debian9的二进制包？

**Comment by 4ever911** [comment]
支持，ubuntu 18.04, 18.10, 按提示编译通不过，已经正确安装了boost，

或者提供一个更详细都编译指南

**Comment by yutiansut** [comment]
现在属于中继模式 其实无所谓了吧……




------------------ 原始邮件 ------------------
发件人: 4ever911 <notifications@github.com>
发送时间: 2019年7月4日 15:20
收件人: shinnytech/open-trade-gateway <open-trade-gateway@noreply.github.com>
抄送: Subscribed <subscribed@noreply.github.com>
主题: 回复：[shinnytech/open-trade-gateway] 二进制分发 (#13)




支持，ubuntu 18.04, 18.10, 按提示编译通不过，已经正确安装了boost，
 
或者提供一个更详细都编译指南
